### PR TITLE
Adding C# Language

### PR DESCRIPTION
**Pull request by hima-Megahed**

### CODE REVIEW

**Comment by floppylab** [comment]
@hima-Megahed  thank you very much! :) 👍

**Comment by floppylab** [comment]
I was wondering if you could make it so that there is not any subfolder in the C# folder? Or is it necessary? What do you think?

**Comment by hima-Megahed** [comment]
It's totally fine I just tried to understand the hierarchy but unfortunately, I couldn't, I thought those folders are required in Java, despite that I could make the same hierarchy if you like, but can you just let me know the reason for this hierarchy is it a pattern you're following or something like that?
I'm eager to hear from you again 😄☕️👍

**Comment by floppylab** [comment]
Check out the code now please. I did not change the structure, but I deleted the unnecessary files. ;) I added git ignore too. It is all good now, thanks again! ;)

**Comment by hima-Megahed** [comment]
Amazing work, well done 👍 I also updated readme with latest changes. Thanks for your high professionality 😄.
Have a nice day with a cup of coffee ☕️🍩.

**Pull request merged**
