### PR TITLE
Issue #20 - Add JavaScript version of hangman

### PR DESCRIPTION
**Pull request by ywpark1**
This is the JavaScript implementation of hangman.

I used fsPromises modules, so node js version 10 or higher is needed to run this program.

Please let me know if there is anything I can improve.

Thanks.

### CODE REVIEW

**Comment by floppylab** [comment]
Thank you very much! I have only one thing, could you please add the node_modules folder to a gitignore file?  Otherwise it looks nice! :)

**Comment by floppylab** [comment]
Plus 1: could you please also add JavaScript to the languages section of the readme of hangman?

**Comment by ywpark1** [comment]
I added node_modules folder to a .gitignore file. Also, added JavaScript in the language section.

Thanks!

**Comment by floppylab** [comment]
Nice! :) Thanks a lot! :)

**Pull request merged**
