### PR TITLE
Add python hangman

### PR DESCRIPTION
**Pull request by Jaco-Minnaar**
added hangman game in python. issue #17

### CODE REVIEW

**Comment by floppylab** [comment]
Thanks! A few things: why is there another words file? I mean the one ending with txt. Also... Could you please mimic the original codebase? You refactored the hangman drawing lines into separate methods and you changed a few variable names. The idea here is to have all the same bugs, mistakes or violations in each implementation! :) So could you please make a few changes on the code?

**Comment by Jaco-Minnaar** [comment]
Of course, apologies, I did not realize that that was what was expected. I shall change the code to that. The other text file was one I used before copying the 'in' file, I'll remove the txt.

**Comment by Jaco-Minnaar** [comment]
I have changed the code to more closely mimic the C# code. Hopefully everything is in order now.

**Comment by floppylab** [comment]
Thank you very much! :) It looks nice! :)

**Pull request merged**
